# Generated by Django 3.2.9 on 2023-08-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarProduct',
        ),
    ]
